on: [push]

jobs:
  check_cves_for_mods:
    runs-on: ubuntu-latest
    name: A job to check for modifications
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run the checker
        uses: ./
        id: check
        with:
          cve-list-path: './cvelist.txt'
      - name: Get the output time
        run: echo "::warning Modified CVEs count = ${{ steps.check.outputs.modified_cves }}"
        if: ${{ steps.check.outputs.modified_cves != '0' }}
